CREATE DATABASE recipeDb;
\c recipeDb;

CREATE TABLE person
(
	id SERIAL NOT NULL PRIMARY KEY,
	firstName VARCHAR(50) NOT NULL,
	lastName  VARCHAR(50) NOT NULL,
	phone     INTEGER NOT NULL,
	email     VARCHAR(100) NOT NULL
);


CREATE USER savannah WITH PASSWORD 'sadautel';
GRANT SELECT, UPDATE, DELETE, INSERT ON sudoku TO jordan;
GRANT USAGE, SELECT ON SEQUENCE sudoku_id_seq TO jordan;